# Avala Enclii Configuration
# Platform-as-a-Service deployment config for Enclii

project: avala
organization: madfam
registry: ghcr.io/madfam-io

# Service definitions
services:
  - name: avala-api
    path: .
    dockerfile: Dockerfile
    port: 3000

  - name: avala-web
    path: .
    dockerfile: Dockerfile.web
    port: 3000

# Environment configurations
environments:
  staging:
    namespace: avala-staging
    domain: staging.avala.studio
    replicas:
      min: 1
      max: 3

  production:
    namespace: avala-production
    domain: avala.studio
    replicas:
      min: 2
      max: 10

# Build settings
build:
  cache: true
  parallel: true

# Deployment settings
deployment:
  strategy: canary
  healthCheckPath: /api/health
  timeout: 300s
